import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: { padding: 44, fontFamily: 'Helvetica', fontSize: 10, color: '#020202', backgroundColor: '#ffffff' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  brandBlock: { flexDirection: 'column', maxWidth: '55%' },
  brandName: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#029aff', marginBottom: 4 },
  sellerDetail: { fontSize: 9, color: '#6b7280', lineHeight: 1.5 },
  invoiceMeta: { alignItems: 'flex-end' },
  invoiceLabel: { fontSize: 8, color: '#9ca3af', letterSpacing: 1.5, marginBottom: 2 },
  invoiceNumber: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: '#020202' },
  statusBadge: { fontSize: 8, marginTop: 4, color: '#029aff', letterSpacing: 1 },
  accentLine: { borderBottomWidth: 2, borderBottomColor: '#029aff', marginBottom: 24 },
  twoCol: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 28 },
  block: { flex: 1 },
  blockLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 6 },
  blockText: { fontSize: 10, color: '#374151', lineHeight: 1.6 },
  table: { marginBottom: 24 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#029aff', padding: '7 10', borderRadius: 4, marginBottom: 1 },
  tableHeaderText: { color: '#ffffff', fontFamily: 'Helvetica-Bold', fontSize: 9 },
  tableRow: { flexDirection: 'row', padding: '6 10', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  tableRowAlt: { flexDirection: 'row', padding: '6 10', backgroundColor: '#f9fafb', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  colDesc: { flex: 4 },
  colQty: { flex: 1, textAlign: 'right' },
  colPrice: { flex: 2, textAlign: 'right' },
  colAmount: { flex: 2, textAlign: 'right' },
  totalsBlock: { alignItems: 'flex-end', marginBottom: 28 },
  totalsRow: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: 4 },
  totalsLabel: { width: 110, textAlign: 'right', color: '#6b7280', marginRight: 20, fontSize: 10 },
  totalsValue: { width: 80, textAlign: 'right', fontSize: 10 },
  totalsBold: { fontFamily: 'Helvetica-Bold', fontSize: 13, color: '#029aff' },
  footer: { position: 'absolute', bottom: 32, left: 44, right: 44, borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 10 },
  footerText: { fontSize: 8, color: '#9ca3af', textAlign: 'center' },
  notesLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 5 },
  notesText: { fontSize: 9, color: '#374151', lineHeight: 1.6 },
})
